/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dut_yangzhou_jnicode_HelloNative */

#ifndef _Included_com_dut_yangzhou_jnicode_HelloNative
#define _Included_com_dut_yangzhou_jnicode_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dut_yangzhou_jnicode_HelloNative
 * Method:    greeting
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_dut_yangzhou_jnicode_HelloNative_greeting
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
